config/routes.rb
Rails.application.routes.draw do
  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end
  
  root "todo_lists#index"
  get 'tags/:tag' => 'todo_items#index', as: :tag
end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  acts_as_taggable
  belongs_to :todo_list
  validates :content, length: { in: 1..255 }
  
  def completed?
    !completed_at.blank?
  end
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  has_many :todo_items
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list, except: [:index]
  before_action :set_todo_item, except: [:create]
  
  def index
    if params[:tag]
      @todo_items = TodoItem.tagged_with(params[:tag])
    else
      @todo_items = TodoItem.all
    end
  end
  
  def create
    @todo_item = @todo_list.todo_items.create(todo_item_params)
    redirect_to @todo_list
  end
  
  def destroy
    if @todo_item.destroy
      flash[:success] = "Todo List was destroyed"
    else
      flash[:error] = "Item could not be destroyed"
    end
    redirect_to @todo_list
  end
  
  def complete
    @todo_item.update_attribute(:completed_at, Time.now)
    redirect_to @todo_list, notice: "To do item completed!"
  end
  
  private
  
  def set_todo_list
    if (params[:todo_list_id].present?)
      @todo_list = TodoList.find(params[:todo_list_id])
    end
  end
  
  def set_todo_item
    if (params[:todo_list_id].present?)
      @todo_item = @todo_list.todo_items.find(params[:id])
    end
  end
  
  def todo_item_params
    params[:todo_item].permit(:content, :tag_list)
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "TODO APP", '#', class: "navbar-brand" %>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li>
        <%= link_to root_path do %>
          <span class="glyphicon glyphicon-home"></span> Home 
        <% end %>
      </li>
      <li>
        <%= link_to new_todo_list_path do %>
          <span class="glyphicon glyphicon-list-alt"></span> New List 
        <% end %>
      </li>
    </ul>
  </div><!--/.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <div class="row">
        <div class="col-sm-4"></div>
        <div class="col-sm-4 text-center">
          <% if !notice.blank? %>
            <p id="notice"><%= notice %></p>
          <% end %>
          <%= yield %>
        </div>
        <div class="col-sm-4"></div>
      </div>
    </div>
  </body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for([@todo_list, @todo_list.todo_items.build], :html => { :class => "form-horizontal" }) do |f| %>
  <%= f.text_field :content, class: "form-control", placeholder: "New Todo" %>
  <%= f.text_field :tag_list, class: "form-control", placeholder: "Tags (separated by commas)" %>
  <%= f.submit "Submit!", class: "btn btn-default" %>
<% end %>

app/views/todo_items/_todo_item.html.erb
<p>
<% if todo_item.completed? %>
  <i class="fa fa-check-square-o"></i>
  <span style="opacity: 0.4;"><strike><%= todo_item.content %></strike></span>

  || Tags: <%= todo_item.tag_list %> ||
  
  <%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: {confirm: "Are you sure?"} do %>
    <i class="fa fa-trash-o"></i>
  <% end %>
  
<% else %>

  <%= link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %>
    <i class="fa fa-square-o"></i>
  <% end %>
  
  <%= todo_item.content %>
  
  || Tags: <%= raw todo_item.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %> ||
  
  <%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: {confirm: "Are you sure?"} do %>
    <i class="fa fa-trash-o"></i>
  <% end %>
<% end %>
</p>

app/views/todo_items/index.html.erb
<h1><%= params[:tag] %></h1>

<% @todo_items.each do |todo_item| %>
  <p>
  <!--Define todo_list-->
  <% @todo_list = todo_item.todo_list %>
  
  <!--If completed-->
  <% if todo_item.completed? %>
    <i class="fa fa-check-square-o"></i>
    <span style="opacity: 0.4;"><strike><%= todo_item.content %></strike></span>
  
  <% else %>
  
    <%= link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %>
      <i class="fa fa-square-o"></i>
    <% end %>
  
    <%= todo_item.content %>

  <% end %>

  <!--Add Tags and Origin-->
  || Tags: <%= raw todo_item.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %> || <%= @todo_list.title %> ||
  
  <!--Delete-->
  <%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: {confirm: "Are you sure?"} do %>
    <i class="fa fa-trash-o"></i>
  <% end %>
  
  </p>
<% end %>

app/views/todo_lists/_form.html.erb
<%= form_for @todo_list, :html => {:class => "form-horizontal"} do |f| %>

  <!--Error Messages-->
  <% if @todo_list.errors.any? %>
    <div class="alert alert-danger text-left">
      <%= pluralize(@todo_list.errors.count, "error") %> prevented the list from being saved:</h2>
      <ul>
      <% @todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <!--List Name-->
  <div class="form-group">
    <%= f.label :title, class: "control-label sr-only" %>
    <%= f.text_field :title, class: "form-control", placeholder: "Name Of Your List" %>
  </div>
  
  <!--List Description-->
  <div class="form-group">
    <%= f.label :description, class: "control-label sr-only" %>
    <%= f.text_area :description, class: "form-control", placeholder: "Describe Your List" %>
  </div>
  
  <!--Submit Button-->
  <%= f.submit "Submit", class: "btn btn-default" %>
<% end %>

app/views/todo_lists/edit.html.erb
<h1>Editing Todo List</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<% provide(:title, "ToDo App") %>
<h1>My Todo Lists</h1>
<table class="table table-hover list-table">
  <thead>
    <td>List Name</td>
    <td>Admin Controls</td>
  </thead>
  <tbody>
    <% @todo_lists.each do |todo_list| %>
      <tr>
        <td class="vert-align"><%= todo_list.title %></td>
        <td class="vert-align">
          <div class="btn-group">
            <%= link_to 'Manage', todo_list, class: "btn btn-default" %>
            <%= link_to 'Destroy', todo_list, class: "btn btn-default", method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </td>
      </tr>
    <% end %>
    <tr>
      <td class="taller" colspan="2"><%= link_to 'Add A New List', new_todo_list_path, class: "btn btn-success" %></td>
    </tr>
    <tr><td colspan="3"></td></tr>
  </tbody>
</table>

app/views/todo_lists/new.html.erb
<h1>New Todo List</h1>

<%= render 'form' %>
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/show.html.erb
<% if @todo_list.todo_items.empty? %>
  <p class="alert alert-warning">You have an empty list. Add some items to your list!</p>
<% end %>

<div>
  <h1>
    <%= @todo_list.title %>
  </h1>
  
  <p class="lead text-center">
    <%= @todo_list.description %>
  </p>
</div>

<div id="todo_items_wrapper">
  <%= render @todo_list.todo_items %>
  <div id="form">
    <%= render "todo_items/form" %>
  </div>
</div>

<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
<%= link_to 'Back', todo_lists_path %>